[workspace]
authors = ["Kendall Park <kendallparkdev@gmail.com>"]
channels = ["pytorch", "conda-forge"]
name = "ImmaculatePerception"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
einops = ">=0.8.2,<0.9"
gcc = ">=12.1.0"
gxx = ">=12.1.0"
ipython = ">=9.9.0,<10"
ipykernel = ">=7.1.0,<8"

[pypi-dependencies]
torch = ">=2.10.0, <3"
torchvision = ">=0.25.0, <0.26"
numpy = ">=2.4.1, <3"
pillow = ">=12.1.0, <13"
datasets = ">=4.5.0, <5"
huggingface-hub = ">=1.3.4, <2"
transformers = ">=5.0.0, <6"
wandb = ">=0.24.0, <0.25"
accelerate = ">=1.1.0, <2"
scikit-learn = ">=1.8.0, <2"
scipy = ">=1.17.0, <2"
matplotlib = ">=3.10.8, <4"
torch-cka = ">=0.21, <0.22"

[target.linux-64.activation]
env = { HF_HOME = "/var/data/.cache/huggingface" }
