[workspace]
authors = ["Kendall Park <kendallparkdev@gmail.com>"]
channels = ["pytorch", "conda-forge"]
name = "ImmaculatePerception"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
einops = ">=0.8.2,<0.9"
gcc = ">=12.1.0"
gxx = ">=12.1.0"

[pypi-dependencies]
torch = ">=2.10.0, <3"
torchvision = ">=0.25.0, <0.26"
numpy = ">=2.4.1, <3"
pillow = ">=12.1.0, <13"
datasets = ">=4.5.0, <5"
huggingface-hub = ">=1.3.4, <2"
transformers = ">=5.0.0, <6"
wandb = ">=0.24.0, <0.25"

[activation]
env = { HF_HOME = "/var/data/.cache/huggingface" }
